before_script:
    # install dependencies
    - gem install compass
    - gem install jpegtran
    - gem install optipng
    - npm install -g grunt-cli bower
script:
    # We want to gate on passing tests and a successful build
    - bower install
    - grunt
